# Site settings
title: Γιώργος Βράκας
email: your-email@domain.com
description: "Giorgos Vracas - web designer & web developer."
baseurl: ""
url: "http://www.vracas.com"

# Build settings
markdown: kramdown
permalink: pretty
