# Site settings
title: Giorgos Vracas
#email: your-email@domain.com
description: "Giorgos Vracas - web designer & web developer."
baseurl: ""
url: "http://vracas.com"

# Build settings
markdown: kramdown
permalink: pretty
